title: pgstef's blog
description: SELECT * FROM pgstef
theme: jekyll-theme-hacker

name: Stefan Fercot
work: Senior Software Engineer
company: Percona
company_url: https://www.percona.com
avatar: https://raw.githubusercontent.com/pgstef/pgstef.github.io/master/images/myAvatar.png

email: pgstef@fercot.be
email_pro: stefan@cos2in.be
mastodon: "@pgstef@fosstodon.org"
linkedin: "in/stefan-fercot"
bluesky: "@pgstef.bsky.social"

timezone: Europe/Brussels
excerpt_separator: "<!--MORE-->"
paginate: 10
paginate_path: "page:num"
exclude: ["README.md", "syntax.md", "_drafts", "_drafts/template.md", "wip"]
show_drafts: false

plugins:
  - jekyll-feed
