title: pgstef's blog
description: SELECT * FROM pgstef
theme: jekyll-theme-hacker

name: Stefan Fercot
work: Database Backup Architect 
company: EDB
avatar: https://raw.githubusercontent.com/pgstef/pgstef.github.io/master/images/myAvatar.png
twitter: pgstef
email: pgstef@fercot.be
mastodon: "@pgstef@fosstodon.org"

timezone: Europe/Brussels
excerpt_separator: "<!--MORE-->"
paginate: 10
paginate_path: "page:num"
exclude: ["README.md", "syntax.md", "_drafts", "_drafts/template.md"]
show_drafts: false

plugins:
  - jekyll-feed
